services:
  api:
    build: ./api
    expose:
      - "3000"
    environment:
      - REDDIT_CLIENT_ID
      - REDDIT_CLIENT_SECRET
      - UNSPLASH_ACCESS_KEY
      - ADMIN_USERNAME
      - ADMIN_PASSWORD
      - JWT_SECRET
    volumes:
      - ./data/api:/app/data

  frontend:
    build: ./frontend
    ports:
      - "3003:80"
    depends_on:
      - api
